app:
  name: "basket api"
  port: 8080
  environment: "development"
  
database:
  host: "localhost"
  port: 5432
  user: "root"
  password: "1234"
  dbname: "basket"

redis:
  host: "localhost"
  port: 5432
  user: "myuser"
  password: "mypassword"
  dbname: "mydb"