version: '3.4'

services:
  discountdb:
    container_name: discountdb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db

  discount.api:
    container_name: discount.api
    environment:
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - discountdb
    ports:
      - "8002:80"

