basePath: /api/v3
definitions:
  models.Product:
    properties:
      category:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      imageFile:
        type: string
      name:
        type: string
      price:
        minLength: 0
        type: string
      sku:
        type: string
      summary:
        type: string
      updated_at:
        type: string
    required:
    - category
    - description
    - imageFile
    - name
    - price
    - sku
    - summary
    type: object
  payload.GetProductSuccess:
    properties:
      code:
        example: 201
        type: integer
      data:
        $ref: '#/definitions/models.Product'
      message:
        example: Get product success
        type: string
      status:
        example: success
        type: string
    type: object
  payload.Response:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: Error message
        type: string
      status:
        example: failed
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: List APIs of UserManagement Service
  termsOfService: http://swagger.io/terms/
  title: UserManagement Service API Document
  version: "1.0"
paths:
  /admin/:
    get:
      consumes:
      - application/json
      description: User create a product
      parameters:
      - description: Email
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.GetProductSuccess'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/payload.Response'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/payload.Response'
      security:
      - ApiKeyAuth: []
      summary: Create a product
      tags:
      - products
  /products:
    get:
      consumes:
      - application/json
      description: List all existing products of store
      parameters:
      - description: Page
        in: path
        name: page
        required: true
        type: string
      - description: Limit
        in: path
        name: limit
        required: true
        type: string
      - description: Currency
        in: path
        name: currency
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/payload.Response'
      summary: List all existing products
      tags:
      - products
  /products/{id}:
    delete:
      consumes:
      - application/json
      description: User delete the product by product ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/payload.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/payload.Response'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/payload.Response'
      security:
      - ApiKeyAuth: []
      summary: Delete a post by ID
      tags:
      - product
    get:
      consumes:
      - application/json
      description: Get a product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      - description: Currency
        in: path
        name: currency
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.GetProductSuccess'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/payload.Response'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/payload.Response'
      summary: Get a product by ID
      tags:
      - products
    patch:
      consumes:
      - application/json
      description: User update product info
      parameters:
      - description: Update post
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/payload.Response'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/payload.Response'
      security:
      - ApiKeyAuth: []
      summary: Update a product
      tags:
      - products
swagger: "2.0"
