version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    env_file:
      - ./app.env

    ports:
      - '6001:27017'
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
