version: '3'
services:
  productdb:
    image: mongo
    container_name: productdb
    restart: always
    env_file:
      - ./app.env

    ports:
      - '6000:27017'
    volumes:
      - productdb:/data/db

volumes:
  productdb:
