basePath: /api/v1
definitions:
  models.CreateDiscountRequest:
    properties:
      amount:
        example: 15
        type: number
      description:
        example: black friday
        type: string
      discount_type:
        example: percent | amount
        type: string
      end_date:
        example: "2023-04-25 00:00:00"
        type: string
      percentage:
        example: 10
        type: number
      product_id:
        example: 5bbdadf782ebac06a695a8e7
        type: string
      product_name:
        example: laptopn thinkpad
        type: string
      quantity:
        example: 100
        type: integer
      start_date:
        example: "2023-04-13 00:00:00"
        type: string
    required:
    - discount_type
    - end_date
    - product_id
    - quantity
    - start_date
    type: object
  models.GenericResponse:
    properties:
      code:
        type: integer
      data: {}
      errors:
        items:
          type: string
        type: array
      message:
        type: string
      success:
        type: boolean
    type: object
  models.UpdateDiscountRequest:
    properties:
      amount:
        example: 15
        type: number
      description:
        example: black friday
        type: string
      discount_type:
        example: percent | amount
        type: string
      end_date:
        example: 25-04-2023
        type: string
      id:
        example: "1"
        type: string
      percentage:
        example: 10
        type: number
      product_id:
        example: 5bbdadf782ebac06a695a8e7
        type: string
      product_name:
        example: laptopn thinkpad
        type: string
      quantity:
        example: 100
        type: integer
      start_date:
        example: 13-04-2023
        type: string
    required:
    - discount_type
    - end_date
    - id
    - product_id
    - quantity
    - start_date
    type: object
host: localhost:8002
info:
  contact: {}
  description: List APIs of UserManagement Service
  termsOfService: http://swagger.io/terms/
  title: Discount Service API Document
  version: "1.0"
paths:
  /discounts:
    get:
      consumes:
      - application/json
      description: Get all discounts in repository.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GenericResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.GenericResponse'
      summary: Get all discounts in repository.
      tags:
      - discount
    patch:
      consumes:
      - application/json
      description: Update coupon
      parameters:
      - description: Update discount
        in: body
        name: discount
        required: true
        schema:
          $ref: '#/definitions/models.UpdateDiscountRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GenericResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.GenericResponse'
      summary: Update coupon
      tags:
      - discount
    post:
      consumes:
      - application/json
      description: Create discount for product
      parameters:
      - description: New discount
        in: body
        name: discount
        required: true
        schema:
          $ref: '#/definitions/models.CreateDiscountRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GenericResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.GenericResponse'
      summary: Create discount for product
      tags:
      - discount
  /discounts/{id}:
    get:
      consumes:
      - application/json
      description: Get discount for product name
      parameters:
      - description: Discount ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GenericResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.GenericResponse'
      summary: Get discount for product name
      tags:
      - discount
  /discounts/{id}}:
    delete:
      consumes:
      - application/json
      description: Delete coupon by product name
      parameters:
      - description: Discount ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GenericResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.GenericResponse'
      summary: Delete coupon by product name
      tags:
      - discount
swagger: "2.0"
