# FROM mongo

# # Install sudo
# RUN apt-get update && \
#     apt-get install -y sudo && \
#     rm -rf /var/lib/apt/lists/*

# # Download key from MongoDB
# RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
# # Thêm kho lưu trữ của MongoDB vào danh sách kho lưu trữ của hệ thống:
# RUN echo "deb http://repo.mongodb.org/apt/ubuntu ubuntu/mongodb-org/3.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.2.list

# # Cập nhật danh sách kho lưu trữ và cài đặt các gói cần thiết:
# RUN sudo apt-get update
# RUN sudo apt-get install -y mongodb-org-shell mongodb-org-tools

# RUN apt-get update && apt-get install -y \
#     mongodb-clients

# CMD ["mongod"]
