version: '3.4'

services:
  catalogdb:
    image: mongodb/mongodb-community-server
    build:
      context: .
      dockerfile: Services/Catalog/internal/infrastructure/mongodb/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Dockerfile

volumes:
  mongo_data: