version: '3.4'

services:
  basketdb:
    container_name: basketdb
    restart: always    
    ports:
      - "27018:27017"
    volumes:
        - mongo_data_basket:/data/db

  basketredis:
    container_name: basketredis
    restart: always    
    ports:
      - "6379:6379"

  basket.api:
    container_name: basket.api
    environment:
      MONGODB_CONNECTION_STRING: mongodb://admin:password@mongodb:27017/baskets
      REDIS_CONNECTION_STRING: redis://redis:6379
    depends_on:
      - basketdb
      - basketredis
    ports:
      - "8001:80"