version: '3.4'

services:
  basketdb:
    container_name: basketdb
    restart: always    
    ports:
        - "6379:6379"

  basket.api:
    container_name: basket.api
    environment:
      - "CacheSettings:ConnectionString=basketdb:6379"
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "8001:80"