version: '3.4'

services:
  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=discount_service
    restart: always
    ports:
      - "5432:5432"
    expose:
        - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  discount.api:
    container_name: discount.api
    environment:
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      discountdb:
        condition: service_healthy
    ports:
      - "8002:8002"
    env_file:
      - ./Services/Discount/internal/config/discount.env  


  nginx.proxy:
    container_name: nginx.proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/sites-available/default.conf
    ports:
      - "80:80"
    depends_on: 
      - discount.api