name: Basket Microservice Docker Image

on: 
  push:
    branches: [ "basket-service" ]
    tags:
      - "*.*.*"
  pull_request:
    branches: [ "master" ]


jobs:
  release:
    runs-on: ubuntu-latest
