name: Basket Microservice Docker Image

on: 
  push:
    branches: [ "basket-service" ]
    tags:
      - "*.*.*"
  pull_request:
    branches: [ "master" ]


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: basket-service

      - name: Set working directory
        run: |
          cd ./src/Services/Basket

      - name: Fetch required Go modules
        run:  go mod download

      - name: Build
        run:  go build -v ./...

      - name: Test
        run: go test -v ./...
