name: Basket Microservice Docker Image

on: 
  push:
    branches: [ "basket-service" ]
    tags:
      - "*.*.*"
  pull_request:
    branches: [ "master" ]


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
