name: Build Basket Microservice

on: 
  push:
    branches: [ "basket-service" ]
    tags:
      - "*.*.*"
      
  pull_request:
    types:
      - closed
      - opened
      - synchronize
    branches: [ "master" ]

  workflow_dispatch:

  repository_dispatch:
    types:
      - Trigger Workflow

  workflow_call:
    inputs:
      ref:
        required: false
        type: string

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build-linux:
    name: Build Basket Linux
    runs-on: ubuntu-latest
    if: ${{ ! failure() && ! cancelled() }}
    steps:
      - name: Display Event Data
        run: |
          echo "Event data:"
          cat $GITHUB_EVENT_PATH
          echo "Output from Extract Data: ${{ steps.get-ref.outputs.repository}}"
          echo "Output from Extract Data: ${{ steps.get-ref.outputs.outputs.branch }}"
     
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set working directory
        run: |
          ls -al
          # export REPOSITORY="${{steps.get-ref.outputs.repository}}"
          # export PULL_MERGE_BRANCH="${{steps.get-ref.outputs.branch}}"
          # echo "Check new at here: $REPOSITORY $PULL_MERGE_BRANCH"
          # echo "TEST_VERSION=my/version/here" >> $GITHUB_ENV
          # echo "TEST_DATE=$(date +%m.%Y)" >> $GITHUB_ENV

          # echo "$REPOSITORY $PULL_MERGE_BRANCH"
          # chmod +x update_repos.sh
          # ./update_repos.sh
          # cat ./config/repositories.conf

          cd ./src/Services/Basket

      - name: Fetch required Go modules
        run: |
          cd ./src/Services/Basket
          go mod download

      - name: Build
        run: |
          cd ./src/Services/Basket
          go build -o basket-api .\cmd\basket-api\main.go

      # - name: Test
      #   run: |
      #     cd ./src/Services/Basket
      #     go test -v ./...


  build-windows:
    name: Build Basket Window
    runs-on: windows-latest
    if: ${{ ! failure() && ! cancelled() }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set working directory
        shell: cmd
        run: |
          cd ./src/Services/Basket
          go mod download

      - name: Fetch required Go modules
        run: |
          cd ./src/Services/Basket
          go mod download
  
      - name: Build
        run: |
          cd ./src/Services/Basket
          go build -o basket-api.exe .\cmd\basket-api\main.go

      - name: Test
        run: |
          go test -v .\test\internal\domain\repositories\Basket.repository_test.go > result.txt
          mkdir logfile
          mv result.txt
          ls -la
      
      - name: Upload test result as artifact
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: log-result
          path: ${{ runner.workspace }}/src/Services/Basket/logfile/*