name: Docker

on:
  push:
      branches: [ "master" ]
      tags:
        - "*.*.*"
        
jobs:
  build_services:
    name: Build all services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Docker Compose
        run: |
          cd ./src
          docker-compose -f docker-compose.yml -f docker-compose.override.yml up --build