name: Prepare new release

on:
  workflow_dispatch:
    inputs:
      serverBump:
        description: "Bump server version"
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - minor
          - patch
      mobileBump:
        description: "Bump mobile build number"
        required: false
        type: boolean


jobs:
  bump_version:
    runs-on: ubuntu-latest

    outputs:
      ref: ${{ steps.push-tag.outputs.commit_long_sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Commit and tag
        id: push-tag
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Thong Hua
          author_email: huavanthong14@gmail.com
          default_author: user_info 
          message: "Version ${{ env.IMMICH_VERSION }}"
          tag: ${{ env.IMMICH_VERSION }}
          push: true

  build-microservice:
    name: Build Basket Linux
    uses: ./.github/workflows/build_basket.yml
    needs: [ bump_version ]
   
  
  prepare_release:
    runs-on: ubuntu-latest
    needs: build-microservice
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ env.IMMICH_VERSION }}
          generate_release_notes: true
          body_path: misc/release/notes.tmpl
          files: |
            src/docker-compose.yml
            src/Docker-compose.Basket.yml

