name: Test

on: 
  push:
    branches: 
      - master
      - catalog-service
      - user-service
      - basket-service
      - "*-service"
    tags:
      - "*.*.*"
      
  pull_request:
    types:
      - closed
      - opened
      - synchronize
    branches: [ "master" ]

  workflow_dispatch:

  repository_dispatch:
    types:
      - Trigger Workflow

  workflow_call:
    inputs:
      ref:
        required: false
        type: string

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  basket-unit-test:
    name: Basket
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/Services/Basket
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Run Basket services
        run: 
          go build -v ./...

      - name: Test
        run: 
          go test -v ./...

  catalog-unit-test:
    name: Catalog
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/Services/Catalog
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Run Basket services
        run: 
          go build -v ./...
