name: Test

on: 
  push:
    branches: [ "master", "basket-service" ]
    tags:
      - "*.*.*"
      
  pull_request:
    types:
      - closed
      - opened
      - synchronize
    branches: [ "master" ]

  workflow_dispatch:

  repository_dispatch:
    types:
      - Trigger Workflow

  workflow_call:
    inputs:
      ref:
        required: false
        type: string

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  basket:
    name: build basket
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/Services/Basket
    if: ${{ ! failure() && ! cancelled() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20
  
      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            $GOPATH/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Run Basket services
        run: 
          go build -v ./...

      - name: Test
        run: 
          go test -v ./...
